#!/bin/sh -e

STORAGE="$1"
shift

if ! command -v caff > /dev/null; then
	echo "caff is required for acaff to work" >&2
	exit 1
fi

if [ ! -d "$STORAGE" -o ! -w "$STORAGE" ]; then
	echo "$STORAGE is not a writeable directory" >&2
	exit 1
fi

if [ -f "$STORAGE/pubs.asc" ]; then
	gpg --import "$STORAGE/pubs.asc"
fi

if [ -f "$STORAGE/keyids" -a $# -eq 0 ]; then
	xargs -a "$STORAGE/keyids" caff --keys-from-gnupg
elif [ $# -gt 0 ]; then
	caff --keys-from-gnupg "$@"
else
	echo "No keyids file and no key ids on the command line" >&2
	exit 1
fi

find ~/.caff/keys -type f -print0 | \
    xargs -0 tar -cjf "$STORAGE/caff.tar.bz2" ~/.caff/gnupghome/pubring.gpg 
